# Generated by Django 5.1.1 on 2025-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Main project screenshot (recommended: 1200x800px)",
                null=True,
                upload_to="portfolio/projects/%Y/%m/",
            ),
        ),
    ]
